language: node_js
node_js:
    - "6"
before_script:
    - if [[ $(node -v) =~ ^v4.* ]]; then export __node_harmony=--harmony; fi
    - yarn global add grunt-cli
script:
    - yarn test
deploy:
    skip_cleanup: true
    provider: script
    script: grunt build:production gh-pages:travis
    on:
        branch: master